// <auto-generated />
using System;
using LeaveManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525075142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagement.API.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Republic Day",
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Independence Day",
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gandhi Jayanti",
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christmas",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveRequestId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveRequestId");

                    b.ToTable("LeaveAuditLogs");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PendingDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeaveTypeId = 1,
                            PendingDays = 0m,
                            TotalDays = 18m,
                            UsedDays = 0m,
                            UserId = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            LeaveTypeId = 2,
                            PendingDays = 0m,
                            TotalDays = 12m,
                            UsedDays = 0m,
                            UserId = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            LeaveTypeId = 3,
                            PendingDays = 0m,
                            TotalDays = 6m,
                            UsedDays = 0m,
                            UserId = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            LeaveTypeId = 1,
                            PendingDays = 0m,
                            TotalDays = 18m,
                            UsedDays = 0m,
                            UserId = 3,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            LeaveTypeId = 2,
                            PendingDays = 0m,
                            TotalDays = 12m,
                            UsedDays = 0m,
                            UserId = 3,
                            Year = 2026
                        },
                        new
                        {
                            Id = 6,
                            LeaveTypeId = 3,
                            PendingDays = 0m,
                            TotalDays = 6m,
                            UsedDays = 0m,
                            UserId = 3,
                            Year = 2026
                        },
                        new
                        {
                            Id = 7,
                            LeaveTypeId = 1,
                            PendingDays = 0m,
                            TotalDays = 18m,
                            UsedDays = 0m,
                            UserId = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 8,
                            LeaveTypeId = 2,
                            PendingDays = 0m,
                            TotalDays = 12m,
                            UsedDays = 0m,
                            UserId = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 9,
                            LeaveTypeId = 3,
                            PendingDays = 0m,
                            TotalDays = 6m,
                            UsedDays = 0m,
                            UserId = 4,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByManagerId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CarryForward")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarryForward = true,
                            Code = "AL",
                            DefaultDays = 18,
                            IsActive = true,
                            Name = "Annual Leave"
                        },
                        new
                        {
                            Id = 2,
                            CarryForward = false,
                            Code = "SL",
                            DefaultDays = 12,
                            IsActive = true,
                            Name = "Sick Leave"
                        },
                        new
                        {
                            Id = 3,
                            CarryForward = false,
                            Code = "CL",
                            DefaultDays = 6,
                            IsActive = true,
                            Name = "Casual Leave"
                        },
                        new
                        {
                            Id = 4,
                            CarryForward = false,
                            Code = "ML",
                            DefaultDays = 90,
                            IsActive = true,
                            Name = "Maternity Leave"
                        });
                });

            modelBuilder.Entity("LeaveManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "HR",
                            Email = "admin@company.com",
                            EmployeeCode = "EMP001",
                            IsActive = true,
                            JoiningDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HR Admin",
                            PasswordHash = "$2a$11$IMrWwrvjoo9FYjZEsFu52O2cw5n1u.yY2gVbPV1FXV5dGagtQPf5C",
                            Role = "HRAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Engineering",
                            Email = "ravi@company.com",
                            EmployeeCode = "EMP002",
                            IsActive = true,
                            JoiningDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerId = 1,
                            Name = "Ravi Kumar",
                            PasswordHash = "$2a$11$IMrWwrvjoo9FYjZEsFu52O2cw5n1u.yY2gVbPV1FXV5dGagtQPf5C",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Engineering",
                            Email = "priya@company.com",
                            EmployeeCode = "EMP003",
                            IsActive = true,
                            JoiningDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerId = 2,
                            Name = "Priya Singh",
                            PasswordHash = "$2a$11$IMrWwrvjoo9FYjZEsFu52O2cw5n1u.yY2gVbPV1FXV5dGagtQPf5C",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Engineering",
                            Email = "arjun@company.com",
                            EmployeeCode = "EMP004",
                            IsActive = true,
                            JoiningDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerId = 2,
                            Name = "Arjun Mehta",
                            PasswordHash = "$2a$11$IMrWwrvjoo9FYjZEsFu52O2cw5n1u.yY2gVbPV1FXV5dGagtQPf5C",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveAuditLog", b =>
                {
                    b.HasOne("LeaveManagement.API.Models.LeaveRequest", "LeaveRequest")
                        .WithMany("AuditLogs")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveBalance", b =>
                {
                    b.HasOne("LeaveManagement.API.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.API.Models.User", "User")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveRequest", b =>
                {
                    b.HasOne("LeaveManagement.API.Models.User", "ApprovedByManager")
                        .WithMany()
                        .HasForeignKey("ApprovedByManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeaveManagement.API.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagement.API.Models.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByManager");

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.User", b =>
                {
                    b.HasOne("LeaveManagement.API.Models.User", "Manager")
                        .WithMany("Reportees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveRequest", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.LeaveType", b =>
                {
                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("LeaveManagement.API.Models.User", b =>
                {
                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Reportees");
                });
#pragma warning restore 612, 618
        }
    }
}
